name: format-tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/3scale/soyuz:v0.3.0-ci
    steps:
      - uses: actions/checkout@v2

      - name: Run docs tests
        run: make test-docs

      - name: Run terraform tests
        run: make test-terraform
